language: php

php:
  - 7.0

install:
  - cp .env.travis .env
  - mysql -e 'create database "program.sch.test";'
  - composer self-update
  - composer install --no-interaction --no-suggest
  - php artisan key:generate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit

notifications:
  email: false
  slack:
      rooms:
        - edems:D8VO6BTDJLNYNznx8YSA3uD3#program_sch
      on_success: change
      on_failure: always