language: php

php:
  - 7.2
  - 7.3

install:
  - cp .env.travis .env
  - mysql -e 'create database program_sch_test;'
  - composer self-update
  - composer install --no-interaction --no-suggest
  - php artisan key:generate
  - php artisan config:cache
  - php artisan laroute:generate
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit

notifications:
  email: false
  slack:
    rooms:
      - edems:D8VO6BTDJLNYNznx8YSA3uD3#program_sch
    on_success: change
    on_failure: always